plugins:
  - jekyll-seo-tag
author: tradies4good
tagline: Trading, Know How, finanzielle Freiheit. Wir lernen das gemeinsam.
twitter:
  username: tradies4good
  title: Tradies Online Community
url: https://blogs.meinetradies.de
site_name: https://www.meinetradies.de
locale: de_DE
description: Tradies - Ein guter Trade
