plugins:
  - jekyll-seo-tag
  - jekyll-feed
author: tradies4good
tagline: Trading, Know How, finanzielle Freiheit. Wir lernen das gemeinsam.
twitter:
  username: tradies4good
  title: Tradies - Gemeinsam traden lernen
url: https://blog.tradies-online.de
site_name: https://www.tradies-online.de
locale: de_DE
description: Tradies - Gemeinsam traden lernen
title: Tradies - Gemeinsam traden lernen
